server:
  #端口号
  port: 8088

spring:
  application:
    name: springcloud-client #服务名称

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #是否注册到eureka服务器
    fetch-registry: true #是否可检索
    service-url:
      defaultZone: http://10.16.85.199:8091/eureka/,http://10.16.85.199:8092/eureka/,http://10.16.85.199:8093/eureka/ #服务中心
